const PREFIX_INCREMENT = 'newsApi/';

export const GET_NEWS_DATA_SUCCESS = `${PREFIX_INCREMENT}REQUEST/GET_NEWS_DATA_SUCCESS`;
export const GET_NEWS_DATA_REQUEST = `${PREFIX_INCREMENT}REQUEST/GET_NEWS_DATA_REQUEST`;
export const GET_NEWS_DATA_FAILURE = `${PREFIX_INCREMENT}REQUEST/GET_NEWS_DATA_FAILURE`;

export const UPDATE_NEWS_TYPE = `${PREFIX_INCREMENT}REQUEST/UPDATE_NEWS_TYPE`;
