const Colors = {
  success: '#09ce89',
  warning: '#ffd03b',
  error: '#e91e45',
  primary: '#556cff',
  darkBlack: '#000000',
  glWhite: '#F2F2F2',
  glGrey: '#707070',
  glLightGrey: '#6A6A6A',
  glBlack: '#2F2F2F',
  glLightBlack: '#383838',
  glOrange: '#FF8C63',
  glOrangeMid: '#FF8B68',
  glOrangeDark: '#FD8C68',
  glButtonOrange: '#FF8C68',
  white: '#FFFFFF',
  greish: 'rgba(0, 0, 0, 0.3)',
  grey: '#B0B0B0',
  glPlaceholder: 'rgba(39, 39, 39, 0.3)',
  glTextLight: 'rgba(39, 39, 39, 0.7)',
  glUserDetail: 'rgba(39, 39, 39, 0.5)',
  glTextGen: '#272727',
  blure: 'rgba(0, 0, 0, 0.85)',
  pWhite: '#F9F7F7',
  pLightBlue: '#DBE2EF',
  pBlue: '#3F72AF',
  pDarkBlue: '#112D4E',
  pTextBlack: '#252a34',
  pTextGrey: '#9999ad',
  pBackOpacity: 'rgba(0, 0, 0, 0.5)',
  pGreen: '#00A300',
  pRed: '#ff1919',
};

const Fonts = {
  muliBlack: 'Muli-Black',
  muliBlackItalic: 'Muli-BlackItalic',
  muliBold: 'Muli-Bold',
  muliBoldItalic: 'Muli-BoldItalic',
  muliExtraBold: 'Muli-ExtraBold',
  muliExtraBoldItalic: 'Muli-ExtraBoldItalic',
  muliExtraLight: 'Muli-ExtraLight',
  muliExtraLightItalic: 'Muli-ExtraLightItalic',
  muliLight: 'Muli-Light',
  muliLightItalic: 'Muli-LightItalic',
  muliRegular: 'Muli-Regular',
  muliRegularItalic: 'Muli-RegularItalic',
  muliSemiBold: 'Muli-SemiBold',
  muliSemiBoldItalic: 'Muli-SemiBoldItalic',
};

module.exports = {
  Fonts,
  Colors,
};
